export const AUTH_RESPONSE_CODE = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_NOT_FINISHED_SIGN_UP: 'USER_NOT_FINISHED_SIGN_UP',
  USER_EXISTED: 'USER_EXISTED',
  USER_NOT_VERIFIED: 'USER_NOT_VERIFIED',
  USER_ACCOUNT_CREATED: 'USER_ACCOUNT_CREATED',
  EMAIL_ALREADY_SENT: 'EMAIL_ALREADY_SENT',
  VERIFICATION_CODE_SENT: 'VERIFICATION_CODE_SENT',
  OTP_INCORRECT: 'OTP_INCORRECT',
  EMAIL_SUCCESSFULLY_VERIFIED: 'EMAIL_SUCCESSFULLY_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  USER_ALREADY_HAS_PASSWORD: 'USER_ALREADY_HAS_PASSWORD',
  PASSWORD_CREATED: 'PASSWORD_CREATED',
  PASSWORD_RESETED: 'PASSWORD_RESETED',
  PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
  LOGOUT: 'LOGOUT',
  LOGIN: 'LOGIN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NO_REFRESH_TOKEN: 'NO_REFRESH_TOKEN',
  NEW_TOKEN_PROVIDED: 'NEW_TOKEN_PROVIDED',
};

export const USER_RESPONSE_CODE = {
  USER_PROFILES_FOUND: 'USER_PROFILES_FOUND',
  USER_STARTUP_PROFILE_DETAIL_NOT_FOUND:
    'USER_STARTUP_PROFILE_DETAIL_NOT_FOUND',
  USER_STARTUP_PROFILE_DETAIL_FOUND: 'USER_STARTUP_PROFILE_DETAIL_FOUND',
};

export const STARTUP_RESPONSE_CODE = {
  STARTUPS_FOUND: 'STARTUPS_FOUND',
  STARTUP_NOT_FOUND: 'STARTUP_NOT_FOUND',
  STARTUP_ALREADY_EXIST: 'STARTUP_ALREADY_EXIST',
  STARTUP_CREATED: 'STARTUP_CREATED',
  SDG_GOAL_INVALID: 'SDG_GOAL_INVALID',
  STARTUP_DETAIL_FOUND: 'STARTUP_DETAIL_FOUND',
  STARTUP_DETAIL_NOT_FOUND: 'STARTUP_DETAIL_NOT_FOUND',
};

export const STARTUP_PROFILE_CODE = {
  USER_STARTUP_PROFILE_DETAIL_FOUND: 'USER_STARTUP_PROFILE_DETAIL_FOUND',
};

export const STARTUP_INVITE_EMAIL_STATUS_RESPONSE_CODE = {
  ALREADY_IN_STARTUP: 'ALREADY_IN_STARTUP',
  ALREADY_BEEN_INVITED: 'ALREADY_BEEN_INVITED',
  NEVER_BEEN_INVITED: 'NEVER_BEEN_INVITED',
};

export const STARTUP_INVITATION_RESPONSE_CODE = {
  FINISH_INVITE: 'FINISH_INVITE',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_INVALID: 'INVITATION_INVALID',
  INVITATION_VALID: 'INVITATION_VALID',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REJECTED: 'INVITATION_REJECTED',
};
